
---
title: "surveyGizmoAPI"
output:
  html_document:
    toc: true
---


```{r}
#This workbook takes a survey gizmo  survey and pulls the result into a long-format table with one value per row, maintaining any nesting of questions/sub-questions for matrix type questions
#Config for Access to Survey Gizmo API
endpoint <- "https://restapi.surveygizmo.com/v5/"
#put entire token and secret string here
apiToken <- ""
#the ID of the survey you want to process followed by a trailing slash
surveyID <- "/"
#category, use if you want to connect a recurrent answer to a particular question ID (in my case, region) that will vary only once per survey. Put it in as a string, e.g. "382"
category <- NA
catVal <- NA
#subcategory, use if you want to connect a recurrent answer to a particular question ID (in my case, country) that will vary only once per survey
subCategory <- NA
subCatVal <- NA
```


```{r}
library(jsonlite)
#get account details
#account <- fromJSON(paste(endpoint,"account?",apiToken,sep=""), simplifyDataFrame = TRUE)
#get list of surveys
#surveyList <- fromJSON(paste(endpoint,"survey?",apiToken,sep=""), simplifyDataFrame = TRUE)
#get a survey by ID
#survey <- fromJSON(paste(endpoint,"survey",surveyID,"?",apiToken,sep=""), simplifyDataFrame = TRUE)
```


```{r}
#get a survey response list by survey ID
getResponseList <- function(endpoint, surveyID, page, apiToken) {
  responseList <- fromJSON(paste(endpoint,"survey/",surveyID,"surveyresponse?page=",page,"&",apiToken,sep=""), simplifyDataFrame = TRUE)
  return(responseList)
}
#get the first page, that will give us the full number of pages to get
responseList <- getResponseList(endpoint, surveyID, 1, apiToken)
#put the ids in a vector
responseIDs <- responseList$data$id
#get ready for page 2 if there is one
page <- 2
#iterate all the pages
while(page <= responseList$total_pages){
  #get the page
  responseList <- getResponseList(endpoint, surveyID, page, apiToken)
  #add all the IDs for the surveys on that page
  responseIDs <- c(responseIDs, responseList$data$id)
  #increment page number
  page <- page + 1
}
```


```{r}
#puts all the survey questions into a frame as some answers in the responses don't seem to list the question!
#generic function to recursively iterate nested data frames
iterateFrame <- function(aFrame, pageTitle) {
  #see if we have an id column
  if(exists('id', where=aFrame) && is.na(aFrame$id) == FALSE && is.integer(aFrame$id)) {
    for (id in aFrame$id) {
      if(nrow(sf) == 0) {
        #use an explicit index to kick off frame population first time, afterward use RBIND which looks to be more threadsafe?
        sf[1,] <<- c(pageTitle, id, aFrame$title$English)
      } else {
        sf <<- rbind(sf, c(pageTitle, id, aFrame$title$English))
      }
    }
  }
  #see if any cells in rows of frame have a nested data frame and recurse if so
  for (row in 1:nrow(aFrame)) {
    iterateList(aFrame[row,], pageTitle)
  }
}
#generic function to iterate lists and see if any item is a dataframe 
iterateList <- function(aList, pageTitle) {
     for (item in aList) {
       if(is.data.frame(item)) {
         #it's a frame, so parse it
         iterateFrame(item, pageTitle)
       } else if(is.list(item)) {
         #if list within a list, recurse
         iterateList(item, pageTitle)
       }
     }
}
#create an empty data frame to hold questions
sf <- data.frame(pageTitle=character(),questionID=integer(), questionTitle=character(), stringsAsFactors=FALSE)

#get all the survey pages
responsePages <- fromJSON(paste(endpoint,"survey/",surveyID,"surveypage?",apiToken,sep=""), simplifyDataFrame = TRUE)
#iterate the pages
for (responsePageID in responsePages$data$id){
  responsePage <- fromJSON(paste(endpoint,"survey/",surveyID,"surveypage/",responsePageID,"?",apiToken,sep=""), simplifyDataFrame = TRUE)
  #iterate the questions in the pages
  iterateList(responsePage$data$questions, responsePage$data$title$English)
}
```


```{r}
#this cell processes each survey response
#note, the code kicks off after all the functions have been defined
library(stringr)

#go through questions in survey
iterateSurvey <- function(timeStamp, surveyResponse, df, catVal, subCatVal) {
  for(response in surveyResponse) {  
      if(response$type!="parent") {
      #some questions have no parent and can be processed into the data frame immediately
        if(nrow(df) == 0) {
          #use an explicit index to kick off frame population first time, afterward use RBIND which looks to be more threadsafe
          df[1,] <- responseToFrame(timeStamp, response, NA, catVal, subCatVal)
        } else {
          df <- rbind(df,responseToFrame(timeStamp, response, NA, catVal, subCatVal))
        }
      } else {
        if(exists('options', where=response)==TRUE) {
          #some parent type questions have a list of option responses, they are a special case
         # str(response)
          for (option in response$options) {
            option$parent <- response$id
            option$question <- response$question
            df <- rbind(df,responseToFrame(timeStamp, option, NA, catVal, subCatVal))
          }
        } else {
          #if child questions go parse those
          df <- doSubResponses(timeStamp, response$subquestions, response$question, catVal, subCatVal, df)
        }
      }
  }
  return(df)
}

#clean ugly strings
cleanString <- function(stringToClean) {
  stringToClean <- str_replace_all(stringToClean, "(</?[^>]+>)","")
  stringToClean <- str_replace_all(stringToClean, "(\\n)"," ")
  stringToClean <- str_replace_all(stringToClean, "( )"," ")
  stringToClean <- str_trim(stringToClean)
  return(stringToClean)
}

#takes a question and returns it as a vector for the data frame
responseToFrame <- function(timeStamp, response, parentQuestion, catVal, subCatVal) {
  #set subQuestion to null, it's only for matrix questions
  parentSubQuestion <- NA
  if(exists('question',where=response) == TRUE) {
     #check for matrix questions and split them into parentSubQuestion/Question on the :
     if(str_detect(response$question, " : ")) {
       multiQuestion <- str_split(response$question, " : ")
       parentSubQuestion <- multiQuestion[[1]][2]
       response$question <- multiQuestion[[1]][1]
     }
     #if answer variable is missing force to null
     if(is.null(response$answer)) {
       response$answer <- NA
     }
     #if question is empty force to Other
     if(response$question == "") {
       response$question <- "Other"
     }
   } 
   #if parent doesn't exist set to null
   if(exists('parent', where=response) == FALSE) {
     response$parent <- NA
   } else if(is.na(parentQuestion)) {
     #if parent exists check to see if parent question exists and go get it if not (bug in the API design)
     parentQuestion <- getSurveyQuestion(response$parent)
   }
   #clean out HTML and \n and such
   response$question <- cleanString(response$question)
   parentQuestion <- cleanString(parentQuestion)
  
   #get the domain
   pageTitle <- NA
   domain <- sf[sf$questionID==response$id,]
   if(nrow(domain)!=0) {
     pageTitle <- domain[1,"pageTitle"]
   } else {
     #try the parent question id
     domain <- sf[sf$questionID==response$parent,]
     if(nrow(domain)!=0) {
       pageTitle <- domain[1,"pageTitle"]
     }
   }
   #write the vector
   row <- c(surveyResponseID, timeStamp, catVal, subCatVal, pageTitle, response$parent, response$id, parentQuestion, parentSubQuestion, response$question, response$answer)
   return (row)
}

#for subquestions. Note this is a recursive function as there can be two levels of subquestions
doSubResponses <- function(timeStamp, subResponses, parentQuestion, catVal, subCatVal, df) {
   for(subResponse in subResponses) {
     if(exists('type', where=subResponse) == TRUE) {
       #since we have a type we know there is not another sub-level, so go ahead and write the row
       df <- rbind(df, responseToFrame(timeStamp, subResponse, parentQuestion, catVal, subCatVal))
     } else {
       #if no type, then we know we have another level to parse so recurse 
       df <- doSubResponses(timeStamp, subResponse, parentQuestion, catVal, subCatVal, df) 
     }   
    }
    return(df)
}

#get details on a survey question as some are listed as parents of a question but not returned in the survey object (e.g. Dropdown Menu List)
getSurveyQuestion <- function (questionID) {
  #check if we already have requested it to cut the number of API calls
  questionRow <- qf[qf$id==questionID,] 
  if(nrow(questionRow)==0) {
    #we don't have any question data so go get it
    surveyQuestion <- fromJSON(paste(endpoint,"survey/",surveyID,"surveyquestion/",questionID,"?",apiToken,sep=""))
    #add it to our question frame
    qf <<- rbind(qf,data.frame(id=surveyQuestion$data$id, question=surveyQuestion$data$title$English, stringsAsFactors = FALSE))
    #get question from frame
    questionRow <- qf[qf$id==questionID,]
  }
  #return the title of question
  return(questionRow$question)
}

#processing really starts here, functions need to be above code that calls them
#create an empty data frame
df <- data.frame(surveyResponseId=integer(), timeStamp=character(), category=character(), subCategory=character(), pageTitle=character(), parentId=integer(), questionId=integer(), parentQuestion=character(), parentSubQuestion=character(), question=character(), value=character(), stringsAsFactors=FALSE)

#a frame to hold survey questions when they are not present in the returned survey, so we don't have to keep hitting it over and over
qf <- data.frame(id=integer(), question=character(), stringsAsFactors=FALSE)

#loop through list of survey responses
for (surveyResponseID in responseIDs){
    #get a survey response by survey ID and response ID
    response <- fromJSON(paste(endpoint,"survey/",surveyID,"surveyresponse/",surveyResponseID,"?",apiToken,sep=""))
    #skip stubs where user tried to login and failed (this is particular to a login scenario, you might need to change this for other survey types)
    if (is.null(response$data$survey_data[[subCategory]]$answer) == FALSE) {
      #these happen to be the fields for region and country in my survey
      if (is.na(category) == FALSE) {
        catVal <- response$data$survey_data[[category]]$answer
      }
      if (is.na(subCategory) == FALSE) {
        subCatVal <- response$data$survey_data[[subCategory]]$answer
      }
      #go through each question adding to data frame
      df <- iterateSurvey(response$data$date_submitted, response$data$survey_data, df, catVal, subCatVal)
    }
}
```


```{r}
#display results
display(df)
```


```{r}
#you don't need these last two cells unless you are monkeying around in data bricks
#save it as a CSV file to the data bricks file system
require(SparkR)
today <- Sys.Date()
format(today, format="%Y%m%d")
#change date delimiter as python doesn't seem to like it
today <- gsub("-", "_", as.character(today))
sparkDF <- createDataFrame(df)
#writes to data bricks default filestore
write.df(sparkDF, path=paste("dbfs:/FileStore/df/sitrep_annex_",today,".csv",sep=""), source="csv", mode="overwrite", header="true")
```


```{r}
#you need python support for this last cell, this was run using data bricks
%python
import datetime
#save it as a parquet table in the data bricks Data store
# File location and type
file_location = "/FileStore/df/sitrep_annex_" + datetime.date.today().strftime('%Y_%m_%d') + ".csv"
file_type = "csv"

# CSV options
infer_schema = "false"
first_row_is_header = "true"
delimiter = ","

# The applied options are for CSV files. For other file types, these will be ignored.
df = spark.read.format(file_type) \
  .option("inferSchema", infer_schema) \
  .option("header", first_row_is_header) \
  .option("sep", delimiter) \
  .load(file_location)

# Create a table, just use the month to avoid getting a copy every day you run it
permanent_table_name = "sitrep_annex_" + datetime.date.today().strftime('%Y_%m')
df.write.mode("overwrite").format("parquet").saveAsTable(permanent_table_name)
```